server:
  port: ${PORT:${SERVER_PORT:8080}}

spring:
  application:
    name: gateway
cloud:
  gateway:
    discovery:
     locator:
        enable: true
    routes:
    - id: api-catalog
      uri: lb://api-catalog
      predicates:
        - Path=/catalog/**
    - id: api-movie
      uri: lb://api-movie
      predicates:
        - Path=/movies/**
info:
  app:
    name: ${spring.application.name}

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: true
    serviceURL:
      defaultZone: http://localhost:8761/eureka
management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: gateway